---
abstract: 'Utility module to return numbers from strings'
author:
  - unknown
build_requires: {}
configure_requires:
  Module::Build: 0.42
dynamic_config: 1
generated_by: 'Module::Build version 0.4204, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: GetNum
provides:
  GetNum:
    file: lib/GetNum.pm
    version: v1.0.1
requires:
  Exporter: 0
  Inline::C: 0
version: v1.0.1
